domain: alfa.verdugo.ru
url: http://alfa.verdugo.ru

encoding: "utf-8"

compress_html:
  clippings: all
  comments: all

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: /:path/:basename/
      lang: "ru"
